[FileDialog]
history=file:///home/autumn/Downloads/ebenezer, file:///home/autumn/Downloads/ebenezer/compressed, file:///home/autumn/Downloads/ignou, file:///home/autumn, file:///home/autumn/Desktop/Web/hmar-media, file:///home/autumn/Drives/B/Backup/pipi/pipi
lastVisited=file:///home/autumn/Drives/B/Backup/pipi/pipi
qtVersion=6.11.1
shortcuts=file:, file:///home/autumn
sidebarWidth=95
treeViewHeader="@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\x2\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1\xd1\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\0\xf5\0\0\0\x1\0\0\0\0\0\0\0\x39\0\0\0\x1\0\0\0\0\0\0\0=\0\0\0\x1\0\0\0\0\0\0\0\x66\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1)"
viewMode=Detail
